import type { NextPage } from 'next'
import Head from 'next/head'
import CarouselA from '../components/elements/carousels/CaouselA'
import HomeA from '../components/sections/HomeA'
import HomeB from '../components/sections/HomeB'
import useStore from '../store'
import HomeC from '../components/sections/HomeC'
import CommentCard from '../components/elements/carousels/CommentCard'

const Home: NextPage = () => {
  const pageNum =useStore((state:any)=>state.pageNum)
  
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        
      </Head>
    {
pageNum===0 ? <><HomeA/> <CommentCard/> <CarouselA/></>  : pageNum===1 ? <HomeB/> : <HomeC/>
    }
      
    </>
  )
}

export default Home

/* Image example :<Image src={Github} alt='Github' width={500} height={200} /> */